name: cdads_example
description: "Demonstrates how to use the cdads_flutter plugin."
publish_to: 'none'

environment:
  sdk: ^3.6.1
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cdads_flutter:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
